name: publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: price-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          scope: "@getdelta"
          registry-url: "https://npm.pkg.github.com/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn install
      - run: yarn check:typescript
      - run: yarn build
      - name: Persist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          scope: "@getdelta"
          registry-url: "https://npm.pkg.github.com/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Grab persisted artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: yarn install
      - name: Publish
        run: yarn publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
